### ISSUE TITLE
Season TODO List 2023 - GHW INIT Challenge

### ISSUE THREAD

**Issue by mannadamay12** [mannadamay12/mannadamay12#1]
- [x] Revamp my portfolio website
- [ ] Attend ML/AI hackthon
- [ ] Organize technical fest in my college
- [ ] Learn Web3 and build at least 3 projects in it
- [ ] Deliver a talk session on any technology
